export const FRUIT = [{name: "apple"}, {name: "banana"}, {name: "lemon"}, {name: "mango"}, {name: "blueberry"}, {name: 'orange'}, {name: 'cherry'}];

export const TEST_PLAYERS = [
    {
        name: "Brian",
        level: 4,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Zeb",
        level: 6,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Carl",
        level: 8,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Nash",
        level: 7,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Mark Q.",
        level: 5,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Maddy",
        level: 3,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Krizzy",
        level: 1,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Francis",
        level: 1,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "BFF Mike G",
        level: 5,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Ivy",
        level: 6,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Ronald",
        level: 6,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Jordan",
        level: 5,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Mike V",
        level: 4,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Jai D",
        level: 4,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Zander",
        level: 4,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Tata",
        level: 1,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Maive",
        level: 7,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Ernest",
        level: 8,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Jovic",
        level: 6,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Duke",
        level: 5,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Moira",
        level: 4,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Riza",
        level: 1,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Alex Q",
        level: 3,
        priority: 0,
        gamesPlayed: 0,
    },
    {
        name: "Cecil",
        level: 1,
        priority: 0,
        gamesPlayed: 0,
    },
];